name: test

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - build
          - test:acceptance
          # - test:unit
          - test:ui
          - test:type
          - test:lint
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - id: yarn_cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
      if: steps.yarn_cache.outputs.cache-hit != 'true'
    - run: yarn ${{matrix.command}}

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: yarn_cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/**/*.*"
        token: ${{ secrets.GITHUB_TOKEN }}
    